---
- name: Install pacman packages.
  become: yes
  pacman: name="{{arch_packages}}" state=present
  

- name: Add powerline to bash config.
  blockinfile:
    path: ~/.bashrc
    content: |
      # Add the powerline to bash, requires it being installed!
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      #. /lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh    

# An AUR plugin will extend our Ansible modules.
- name: Clone AUR plugin for Ansible
  become: yes
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur
  when: install_aur_packages

# Create AUR build user.
# See plugin homepage for details.
# https://github.com/kewlfft/ansible-aur
- name: Create AUR build user, as root is not permitted
  become: yes
  user:
    name: aur_builder
    group: wheel
  when: install_aur_packages

- name: Configure AUR user to run pacman
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  when: install_aur_packages

- name: Configure lightdm-theme Litarvan
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regex: '^webkit_theme'
    line: 'webkit_theme        = litarvan'

