---
- name: Install pacman packages.
  become: yes
  pacman: name="{{arch_packages}}" state=present

- name: Install the San Francisco Font to system fonts.
  become: yes
  unarchive:
    src: '{{fonts_download}}'
    dest: '/usr/share/fonts'
    remote_src: yes
  tags: fonts
  register: font_installed

- name: Clear font cache
  become: yes
  command: fc-cache -f -v
  tags: fonts
  when: font_installed.changed == True

- name: Add powerline to bash config.
  blockinfile:
    path: ~/.bashrc
    content: |
      # Add the powerline to bash, requires it being installed!
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      #. /lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh

# Extract the spacemacs to my normal user's home.
- name: Spacemacs setup from online repo.
  become: yes
  become_user: martin
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

# An AUR plugin will extend our Ansible modules.
- name: Clone AUR plugin for Ansible
  become: yes
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur
  when: install_aur_packages
  tags: aursetup

# Create AUR build user.
# See plugin homepage for details.
# https://github.com/kewlfft/ansible-aur
- name: Create AUR build user, as root is not permitted
  become: yes
  user:
    name: aur_builder
    group: wheel
  when: install_aur_packages
  tags: aursetup

- name: Configure AUR user to run pacman
  become: yes
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  when: install_aur_packages
  tags: aursetup

- name: Configure lightdm-theme Litarvan
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regex: '^webkit_theme'
    line: 'webkit_theme        = litarvan'
