---
# These are the packages to install
arch_packages:
  - bash-completion
  - neovim
  - ansible
  - pandoc
  - rxvt-unicode
  - git
  - qutebrowser
  - ranger
  - qutebrowser
  - atool
  - highlight
  - w3m
  - gzip
  - p7zip
  - tar
  - zip
  - unzip
  - unrar
  - ttf-inconsolata
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-fira-code
  - ttf-fira-mono
  - ttf-fira-sans
  - ttf-linux-libertine
  - ttf-ubuntu-font-family
  - ttf-roboto
  - dkms
  - linux-headers
  - arc-gtk-theme
  - moka-icon-theme
  - thunar
  - rofi
  - feh
  - i3blocks
  - scrot
  - powerline
  - python-pip
  - neofetch
  - lightdm-webkit-theme-litarvan
  - gimp
  - sysstat
  - tumbler
  - texlive-core
  - texlive-fontsextra
  - texlive-latexextra
  - lollypop
  - the_silver_searcher
  - emacs
  - jdk-openjdk

arch_aur_packages:
  - gotop
  - yay
  - visual-studio-code-bin
  - bibata-cursor-theme
  - plantuml

arch_python_dev_packages:
  - python-pandas
  - python-xlrd
  - python-matplotlib
  - python-pilkit
  - python-pygraphviz
  - graphviz

pip_python_packages:
  - jira

fonts_download: https://github.com/supermarin/YosemiteSanFranciscoFont/archive/master.zip
