---
- hosts: all
  connection: local

  vars_files:
    - config.settings.yml
    - config.packages.yml

  tasks:
    - include_tasks: tasks/base_setup.yml
    - include_tasks: tasks/install_aur_packages.yml
      when: install_aur_packages
