---
- hosts: all
  connection: local

  vars_files:
    - config.settings.yml
    - config.packages.yml
    - config.dotfiles.yml

  tasks:
    - include_tasks: tasks/base_dotfiles.yml
      when: symlink_dotfiles|bool
      tags: dotfiles
    - include_tasks: tasks/base_setup.yml
      tags:
        - fonts
        - aursetup
    - include_tasks: tasks/install_aur_packages.yml
      when: install_aur_packages|bool
      tags: aur
    - include_tasks: tasks/install_python_packages.yml
      when: install_python_dev|bool
