---
- name: Install pacman packages.
  become: yes
  pacman: name="{{arch_packages}}" state=present
  

- name: Add powerline to bash config.
  blockinfile:
    path: ~/.bashrc
    content: |
      # Add the powerline to bash, requires it being installed!
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      . /lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh    

# An AUR plugin will extend our Ansible modules.
- name: Clone AUR plugin for Ansible
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur

# Create AUR build user.
# See plugin homepage for details.
# https://github.com/kewlfft/ansible-aur
- user:
    name: aur_builder
    group: wheel
- lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

# Install AUR packages.
- name: Install AUR packages.
  aur: name="{{arch_aur_packages}}" use=makepkg skip_installed=true
  become: yes
  become_user: aur_builder

- name: Configure lightdm-theme Litarvan
  become: yes
  lineinfile:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    regex: '^webkit_theme'
    line: 'webkit_theme        = litarvan'

