---
- name: Add powerline to bash config.
  blockinfile:
    path: ~/.bashrc
    content: |
      # Add the powerline to bash, requires it being installed!
      # on Ubuntu you may need a sudo apt-get install powerline
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      . ~/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh    


