---
- name: Install pacman packages.
  become: yes
  pacman: name="{{ arch_packages }}" state=present
  

- name: Add powerline to bash config.
  blockinfile:
    path: ~/.bashrc
    content: |
      # Add the powerline to bash, requires it being installed!
      powerline-daemon -q
      POWERLINE_BASH_CONTINUATION=1
      POWERLINE_BASH_SELECT=1
      . /lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh    


